variable "ami-prod" {}
variable "subnet_id" {}
variable "asg-sg" {}
variable "keyname" {}
variable "name" {}
variable "nexus-ip-prd" {}
variable "nr-acc-id-prd" {}
variable "nr-region-prd" {}
variable "nr-key-prd" {}