variable "ami-stage" {}
variable "asg-sg" {}
variable "keyname" {}
variable "nexus-ip-stage" {}
variable "nr-key-stage" {}
variable "nr-acc-id-stage" {}
variable "nr-region-stage" {}
variable "vpc-zone-id-stage" {}
variable "tg-arn" {}
variable "asg-stage-name" {}