variable "ami-stage" {}
variable "asg-sg" {}
variable "keyname" {}
variable "name" {}
variable "nexus-ip-prd" {}
variable "nr-acc-id-prd" {}
variable "nr-region-prd" {}
variable "nr-key-prd" {}
variable "vpc-zone-id-stage" {}
variable "tg-arn" {}
variable "asg-stage-name" {}